name: Reusable Deploy
# ジョブから呼び出されるワークフローを定義できる。その場合は下記のようにGithubイベントをトリガーとして設定する
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
        working-directory: app/009_reusable/end
      - name: Output information
        run: echo "Deploying & uploading..."